name: Vérification du code PHP

on:
  push:
    branches:
      - evaluation-mes-dates
  pull_request:
    branches:
      - master

jobs:
  phpcs:
    name: Lint PHP Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer PHP et PHPCS
        run: |
          sudo apt-get update
          sudo apt-get install -y php-cli
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          chmod +x phpcs.phar
          sudo mv phpcs.phar /usr/local/bin/phpcs

      - name: Exécuter PHPCS
        run: phpcs --standard=PSR12 index.php MesDates.php
